[platformio]
default_envs = teensy40

[env]
platform = teensy
board = teensy40
framework = arduino
monitor_speed = 115200
build_flags =
    -D USB_MIDI_SERIAL
    -D CORE_DEBUG_LEVEL=0

[env:teensy40]
build_flags =
    ${env.build_flags}
    -D ENABLE_HEIGHT_SENSOR=1
    -D ENABLE_DIAGNOSTICS=0
lib_deps =
    https://github.com/pololu/vl53l4cd-arduino.git#1.0.0

[env:teensy40_debug]
build_flags =
    ${env.build_flags}
    -D ENABLE_HEIGHT_SENSOR=1
    -D ENABLE_DIAGNOSTICS=1
lib_deps =
    https://github.com/pololu/vl53l4cd-arduino.git#1.0.0

[env:teensy40_no_height]
build_flags =
    ${env.build_flags}
    -D ENABLE_HEIGHT_SENSOR=0
    -D ENABLE_DIAGNOSTICS=1

[env:native]
platform = native
test_framework = custom
build_src_filter = -<*>
build_flags = -std=c++17
